- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 10.10.11.112
      username: administrator@ucmcswg.com
      password: vmware
      validate_certs: False
      name: testvm_2
      template: RHEL-8-3-min-tmpl
      datacenter: datacenter
      folder: /SHENIYAS/
      state: poweredon
      wait_for_ip_address: no
